dynamicgraph::python::entity Namespace Reference
dynamicgraph::python::entity Namespace Reference
Functions
PyObject * create (PyObject *, PyObject *args)
Create an instance of Entity.
PyObject * display (PyObject *self, PyObject *args)
PyObject * getName (PyObject *, PyObject *args)
Get name of entity.
PyObject * hasSignal (PyObject *, PyObject *args)
Check if the entity has a signal with the given name.
PyObject * getSignal (PyObject *, PyObject *args)
Get a signal by name.
PyObject * listSignals (PyObject *self, PyObject *args)
PyObject * executeCommand (PyObject *self, PyObject *args)
PyObject * listCommands (PyObject *self, PyObject *args)
PyObject * getCommandDocstring (PyObject *self, PyObject *args)
PyObject * getDocString (PyObject *self, PyObject *args)
Function Documentation
PyObject * dynamicgraph::python::entity::create (PyObject * self, PyObject * args)
Create an instance of Entity.
References CATCH_ALL_EXCEPTIONS, dynamicgraph::Entity::getClassName(), dynamicgraph::PoolStorage::getInstance(), dynamicgraph::FactoryStorage::getInstance(), and dynamicgraph::FactoryStorage::newEntity().
PyObject * dynamicgraph::python::entity::display (PyObject * self, PyObject * args)
References dynamicgraph::Entity::display().
PyObject * dynamicgraph::python::entity::executeCommand (PyObject * self, PyObject * args)
References CATCH_ALL_EXCEPTIONS, dynamicgraph::command::Command::execute(), dynamicgraph::Entity::getName(), dynamicgraph::Entity::getNewStyleCommandMap(), dynamicgraph::python::convert::pythonToValue(), dynamicgraph::command::Command::setParameterValues(), dynamicgraph::python::convert::valueToPython(), and dynamicgraph::command::Command::valueTypes().
PyObject * dynamicgraph::python::entity::getCommandDocstring (PyObject * self, PyObject * args)
References dynamicgraph::command::Command::getDocstring(), dynamicgraph::Entity::getName(), and dynamicgraph::Entity::getNewStyleCommandMap().
PyObject * dynamicgraph::python::entity::getDocString (PyObject * self, PyObject * args)
References dynamicgraph::Entity::getDocString().
PyObject * dynamicgraph::python::entity::getName (PyObject * self, PyObject * args)
Get name of entity.
References CATCH_ALL_EXCEPTIONS, and dynamicgraph::Entity::getName().
PyObject * dynamicgraph::python::entity::getSignal (PyObject * self, PyObject * args)
Get a signal by name.
References CATCH_ALL_EXCEPTIONS, and dynamicgraph::Entity::getSignal().
PyObject * dynamicgraph::python::entity::hasSignal (PyObject * self, PyObject * args)
Check if the entity has a signal with the given name.
References CATCH_ALL_EXCEPTIONS, and dynamicgraph::Entity::hasSignal().
PyObject * dynamicgraph::python::entity::listCommands (PyObject * self, PyObject * args)
References dynamicgraph::Entity::getNewStyleCommandMap().
PyObject * dynamicgraph::python::entity::listSignals (PyObject * self, PyObject * args)
References CATCH_ALL_EXCEPTIONS, and dynamicgraph::Entity::getSignalMap().