dynamicgraph::python Namespace Reference
dynamicgraph::python Namespace Reference
Namespaces
convert
entity
factory
pool
signalBase
signalCaster
Classes
class ExceptionPython
Generic error class.
class Interpreter
This class implements a basis python interpreter.
Functions
PyObject * plug (PyObject *, PyObject *args)
plug a signal into another one.
PyObject * enableTrace (PyObject *, PyObject *args)
std::string parse_python_exception ()
bool HandleErr (std::string &err, PyObject *traceback_format_exception, PyObject *globals_, int PythonInputType)
Variables
PyObject * dgpyError
static const std::string pythonPrefix [5]
Function Documentation
PyObject* dynamicgraph::python::enableTrace (PyObject * , PyObject * args)
References CATCH_ALL_EXCEPTIONS, dynamicgraph::DebugTrace::closeFile(), and dynamicgraph::DebugTrace::openFile().
bool dynamicgraph::python::HandleErr (std::string & err, PyObject * traceback_format_exception, PyObject * globals_, int PythonInputType)
References dgDEBUG, dgDEBUGIN, and dgDEBUGOUT.
Referenced by dynamicgraph::python::Interpreter::python().
std::string dynamicgraph::python::parse_python_exception ()
Referenced by dynamicgraph::python::Interpreter::runPythonFile().
PyObject* dynamicgraph::python::plug (PyObject * , PyObject * args)
plug a signal into another one.
References CATCH_ALL_EXCEPTIONS, and SignalBase< int >::plug().
Variable Documentation
PyObject * dynamicgraph::python::dgpyError
Referenced by initwrap().
const std::string dynamicgraph::python::pythonPrefix[5] static
Initial value:
= {
  "import traceback\n",
  "def display(s): return str(s) if not s is None else None",
  "class StdoutCatcher:\n"
  "    def __init__(self):\n"
  "        self.data = ''\n"
  "    def write(self, stuff):\n"
  "        self.data = self.data + stuff\n"
  "    def fetch(self):\n"
  "        s = self.data[:]\n"
  "        self.data = ''\n"
  "        return s\n"
  "stdout_catcher = StdoutCatcher()\n"
  "import sys\n"
  "sys.stdout = stdout_catcher"
}
Referenced by dynamicgraph::python::Interpreter::Interpreter().