dynamicgraph::python::convert Namespace Reference
dynamicgraph::python::convert Namespace Reference
Functions
void fillMatrixRow (Matrix &m, unsigned iRow, PyObject *tuple)
void fillMatrixRow (Eigen::Matrix4d &m, unsigned iRow, PyObject *tuple)
command::Value pythonToValue (PyObject *pyObject, const command::Value::Type &valueType)
PyObject * vectorToPython (const Vector &vector)
PyObject * matrixToPython (const Matrix &matrix)
PyObject * matrix4dToPython (const Eigen::Matrix4d &matrix)
PyObject * valueToPython (const command::Value &value)
PyObject * matrixToPython (const ::dynamicgraph::Matrix &matrix)
PyObject * valueToPython (const ::dynamicgraph::command::Value &value)
Function Documentation
void dynamicgraph::python::convert::fillMatrixRow (Matrix & m, unsigned iRow, PyObject * tuple)
References dynamicgraph::python::ExceptionPython::MATRIX_PARSING.
Referenced by pythonToValue().
void dynamicgraph::python::convert::fillMatrixRow (Eigen::Matrix4d & m, unsigned iRow, PyObject * tuple)
References dynamicgraph::python::ExceptionPython::MATRIX_PARSING.
PyObject * dynamicgraph::python::convert::matrix4dToPython (const Eigen::Matrix4d & matrix)
Referenced by valueToPython().
PyObject* dynamicgraph::python::convert::matrixToPython (const ::dynamicgraph::Matrix & matrix)
PyObject* dynamicgraph::python::convert::matrixToPython (const Matrix & matrix)
Referenced by dynamicgraph::python::signalBase::getValue(), and valueToPython().
command::Value dynamicgraph::python::convert::pythonToValue (PyObject * pyObject, const command::Value::Type & valueType)
References fillMatrixRow(), dynamicgraph::python::ExceptionPython::MATRIX_PARSING, dynamicgraph::python::ExceptionPython::VALUE_PARSING, and dynamicgraph::python::ExceptionPython::VECTOR_PARSING.
Referenced by dynamicgraph::python::entity::executeCommand().
PyObject* dynamicgraph::python::convert::valueToPython (const ::dynamicgraph::command::Value & value)
PyObject* dynamicgraph::python::convert::valueToPython (const command::Value & value)
References matrix4dToPython(), matrixToPython(), dynamicgraph::command::Value::type(), dynamicgraph::command::Value::value(), and vectorToPython().
Referenced by dynamicgraph::python::entity::executeCommand().
PyObject * dynamicgraph::python::convert::vectorToPython (const Vector & vector)
Referenced by dynamicgraph::python::signalBase::getValue(), and valueToPython().