dynamicgraph::python::signalBase Namespace Reference
dynamicgraph::python::signalBase Namespace Reference
Functions
PyObject * create (PyObject *, PyObject *args)
Create an instance of SignalBase.
PyObject * getTime (PyObject *self, PyObject *args)
PyObject * setTime (PyObject *self, PyObject *args)
PyObject * getName (PyObject *self, PyObject *args)
PyObject * getClassName (PyObject *self, PyObject *args)
PyObject * display (PyObject *self, PyObject *args)
PyObject * displayDependencies (PyObject *self, PyObject *args)
PyObject * getValue (PyObject *self, PyObject *args)
PyObject * setValue (PyObject *self, PyObject *args)
PyObject * recompute (PyObject *self, PyObject *args)
PyObject * unplug (PyObject *self, PyObject *args)
PyObject * isPlugged (PyObject *self, PyObject *args)
PyObject * getPlugged (PyObject *self, PyObject *args)
static void destroy (void *self)
Destroy an instance of InvertedPendulum.
Function Documentation
PyObject * dynamicgraph::python::signalBase::create (PyObject * self, PyObject * args)
Create an instance of SignalBase.
References destroy().
static void dynamicgraph::python::signalBase::destroy (void * self) static
Destroy an instance of InvertedPendulum.
Referenced by create().
PyObject * dynamicgraph::python::signalBase::display (PyObject * self, PyObject * args)
References CATCH_ALL_EXCEPTIONS, and SignalBase< int >::display().
PyObject * dynamicgraph::python::signalBase::displayDependencies (PyObject * self, PyObject * args)
References CATCH_ALL_EXCEPTIONS, and SignalBase< int >::displayDependencies().
PyObject * dynamicgraph::python::signalBase::getClassName (PyObject * self, PyObject * args)
References CATCH_ALL_EXCEPTIONS, and SignalBase< int >::getClassName().
PyObject * dynamicgraph::python::signalBase::getName (PyObject * self, PyObject * args)
References CATCH_ALL_EXCEPTIONS, and SignalBase< int >::getName().
PyObject * dynamicgraph::python::signalBase::getPlugged (PyObject * self, PyObject * args)
References CATCH_ALL_EXCEPTIONS, SignalBase< int >::getName(), SignalBase< int >::getPluged(), and SignalBase< int >::isPlugged().
PyObject * dynamicgraph::python::signalBase::getTime (PyObject * self, PyObject * args)
References SignalBase< int >::getTime().
PyObject * dynamicgraph::python::signalBase::getValue (PyObject * self, PyObject * args)
References dynamicgraph::Signal< T, Time >::accessCopy(), CATCH_ALL_EXCEPTIONS, SignalBase< int >::get(), dynamicgraph::ExceptionAbstract::getCode(), dynamicgraph::python::convert::matrixToPython(), dynamicgraph::ExceptionSignal::PLUG_IMPOSSIBLE, and dynamicgraph::python::convert::vectorToPython().
PyObject * dynamicgraph::python::signalBase::isPlugged (PyObject * self, PyObject * args)
References CATCH_ALL_EXCEPTIONS, and SignalBase< int >::isPlugged().
PyObject * dynamicgraph::python::signalBase::recompute (PyObject * self, PyObject * args)
References CATCH_ALL_EXCEPTIONS, and SignalBase< int >::recompute().
PyObject * dynamicgraph::python::signalBase::setTime (PyObject * self, PyObject * args)
References SignalBase< int >::setTime().
PyObject * dynamicgraph::python::signalBase::setValue (PyObject * self, PyObject * args)
References CATCH_ALL_EXCEPTIONS, and SignalBase< int >::set().
PyObject * dynamicgraph::python::signalBase::unplug (PyObject * self, PyObject * args)
References CATCH_ALL_EXCEPTIONS, and SignalBase< int >::unplug().